### ISSUE TITLE
False positive import detection

### ISSUE THREAD

**Issue by EgZvor** [mgedmin/python-imports.vim#11]
If new import is supposed to go into already existing parenthesized `from` statement then a line to add it looks like this

```
    module_name,
```

the plugin checks for this line in an entire file. This line may exist already and have nothing to do with importing. E.g.

```
from fixtures import (
    fake_db,
    fake_network,
)

__fixtures__ = [
    fake_db,
    fake_network,
    |fake_user,
]
```
`fake_user` will not be imported because the line that would be added is the same as the one that exists already.

**Comment by mgedmin** [comment]
This should be fixed in git master.
