### ISSUE TITLE
Auto import of standard library modules not working when Python is installed not in /usr/lib but elsewhere

### ISSUE THREAD

**Issue by rbhanot4739** [mgedmin/python-imports.vim#3]
I am using Neovim 0.3.2 with python3.7 and installed the plugin and its dependency but the auto import does not seem to work when i do `ImportName`. Below is my setup

	Plug 'ludovicchabant/vim-gutentags'
	Plug 'mgedmin/python-imports.vim'

So if i type `os.listdir()` in a python3 file and then do `:ImportName` it throws me error saying `tag not found for os`. The same thing happens for every other standard library module. I have a valid tag generated and it works fine when i jump for custom modules.

So can you please help on this.

**Comment by daliusd** [comment]
I have tried out this with nvim 0.2.2 (on Ubuntu) and it works fine for me. Look into the code of plugin here https://github.com/mgedmin/python-imports.vim/blob/master/plugin/python-imports.vim . It seems `IsStdlibModule` is returning 0 in your case. You should investigate that.

**Comment by rbhanot4739** [comment]
Not really sure how would i investigate that can you please guide, also why would that happen only in python3 as it works fine with python2.

**Comment by daliusd** [comment]
First check if folder /usr/lib/python/3.7 exists. Then check if /usr/lib/python/3.7/os.py exists.

**Comment by rbhanot4739** [comment]
Ofcourse it exists and just to reiterate it is not happening just for `os` but every standard library module.

**Comment by daliusd** [comment]
You can add echo statements to plugin and use ":messages" command to investigate what's happening in your system :smile:

**Comment by rbhanot4739** [comment]
ok, i guess the problem is this line in the `python-imports.vim` 
`    exec s:python "vim.command(\"let g:pythonStdlibPath = '/usr/lib/python%d.%d'\" % sys.version_info[:2])"`

It is actually hard coding the path to `/usr/lib/python` which i think it should not, in my case i am using conda env and have it installed it in a different location so the plugins simply sets the `pythonStdlibPath` to `/usr/lib/python3.7` which does not exist on my machine. There should be a better way of doing it.

**Comment by mgedmin** [comment]
Temporarily you should be able to work around this by setting `let g:pythonStdlibPath = '/where/your/python/stdlib/is'`, after the script's been loaded.

I should absolutely make this path detection code more robust.  Out of curiosity, where _is_ your Python stdlib located?  And what do `:pyx import sys; print(sys.prefix)` and `:pyx import sys; print(sys.real_prefix)` output in Vim?

**Comment by mgedmin** [comment]
Also, what is your OS/distro?  I suspect the `filereadable(g:pythonStdlibPath . "/lib-dynload/" . a:name . ".so")` check would not work right on, say, Mac OS X.

**Comment by mgedmin** [comment]
(That check doesn't even work on Linux any more, now that the so files can have platform name suffixes, e.g. `bz2.x86_64-linux-gnu.so`!)

**Comment by rbhanot4739** [comment]
I am using Ubuntu 16.04 LTS and since i am using conda for managing my virtual envs the stdlib resides at  `~/tools/miniconda3/envs/py37/lib/python3.7/`. `:python import sys; print(sys.prefix)` returns `tools/miniconda3/envs/py37`.

**Comment by rbhanot4739** [comment]
Infact the workaround won't work since i use multiple conda envs so not sure how and where i can update `let g:pythonStdlibPath`.

**Comment by daliusd** [comment]
Workaround will work. There is very low probability that each virtual env has different standard modules.

**Comment by rbhanot4739** [comment]
Ohh... My bad, i don't know what I was thinking when i made the comment. Sorry!!

**Comment by mgedmin** [comment]
I've updated the stdlib path detection to rely on `sys.prefix`.

I'm very surprised to see that your sys.prefix is not an absolute path.  Please test and let me know if my changes fix the problem for you.

**Comment by rbhanot4739** [comment]
Hey.. Sorry for the confusion, `sys.prefix` returns absolute path only i just trimmed it to refer to my home directory. Secondly i tried to reintall the plugin and I am getting this error.
```

Error detected while processing /spare/ssd/rbhanot/.config/nvim/plugged/python-imports.vim/plugin/python-imports.vim:                                                                                               
line   62:                                                                                                                                                                                                          
E117: Unknown function: pyxeval
```

    if !exists("g:pythonExtModuleSuffix")
        exec s:python "import sysconfig"
        let g:pythonExtModuleSuffix = pyxeval("sysconfig.get_config_var('EXT_SUFFIX') or '.so'")
    endif

Surprisingly i don't see this change at [8d41483](https://github.com/mgedmin/python-imports.vim/commit/8d41483eb033b3d57301419486238f280b12eba0)

**Comment by rbhanot4739** [comment]
I just pulled your change and it worked, however there is one issue, when i hit `:ImportName` it doe not import at the top of the file. See below
**Case 1**
```
print("hello world")
subprocess.run("ls")
print(os.listdir())
```
**Code after doing `:ImportName`**

```
print("hello world")
subprocess.run("ls")
import subprocess
import os
print(os.listdir())

```
**Case 2**
```
print(os.listdir())
subprocess.run("ls")
```
**Code after doing `:ImportName`**
```
print(os.listdir())
import subprocess
import os
subprocess.run("ls")
```
Its behaving weirdly and adding `import` statements randomly, at times above the actual line an other times below as shown above.

**Comment by daliusd** [comment]
@rbhanot4739 Same here but that's separate issue. Again this is not real-life file. Usually this plugin handles real-life files quite well. Drop into this ALE with isort enabled or vim-isort plugin (ALE recommended) and that will cover 99% of your cases.

**Comment by rbhanot4739** [comment]
> Again this is not real-life file. Usually this plugin handles real-life files quite well. Drop into this ALE with isort enabled or vim-isort plugin (ALE recommended) and that will cover 99% of your cases.

I am already using ALE, what you mean by _drop into ALE_ . I am not really sure if i agree with your statement regarding this is not a real life file. Any python file with above 2 lines can be considered a valid real life file which aims to solve a very simple problem of listing directory contents by two different methods.

Should I open a new issue for this ?

**Comment by daliusd** [comment]
@rbhanot4739 

Something like this (isort must be installed):

```
let g:ale_fixers = {
\   '*': ['remove_trailing_lines', 'trim_whitespace'],
\   'python': ['isort'],
\}
```

Feel free to create new issue if you need that. By real-life I mean that file usually has at least one import statement - you rarely write something from the beginning. I believe this plugin does not handle the case when there are no import statements in the file.

**Comment by rbhanot4739** [comment]
@daliusd 


> I believe this plugin does not handle the case when there are no import statements in the file.

You are right in believing this. Though its not very common case but personally i find myself writing code lot of times and then would wish module to be imported when i am actually using something from that module.

Thanks for your help man !!

**Comment by rbhanot4739** [comment]
I think i will open this as a new issue.

**Comment by mgedmin** [comment]
Huh, so neovim doesn't have pyxeval()?  That's a shame, I'll have to do something else then.

Does neovim have pyeval() and py3eval()?

**Comment by mgedmin** [comment]
(The location code for placing new imports is a Very Terrible Hack (TM) that works fine in 80% of case, and to fix the remaining 20% I'd have to rewrite all of it in Python instead of vimscript.  It's been on my to-do list for a long time, and will probably stay there for even longer.)

**Comment by mgedmin** [comment]
> Huh, so neovim doesn't have pyxeval()? That's a shame, I'll have to do something else then.

Fixed in 49fd984849e5259196b250d73f42fd568a3c3aa4.

**Comment by rbhanot4739** [comment]
> (The location code for placing new imports is a Very Terrible Hack (TM) that works fine in 80% of case, and to fix the remaining 20% I'd have to rewrite all of it in Python instead of vimscript. It's been on my to-do list for a long time, and will probably stay there for even longer.)

Can you please explain the hack, because for now it seems to add import statements randomly  even if there is a import statement at the top of the file.

**Comment by rbhanot4739** [comment]
@mgedmin  Hey sorry for bugging you again on this, it looks like my site-packages are not being imported with `tag not found` which seems logical since `tags` file does not have python third party modules since my conda env is at a different location.

So how can i fix this ?  I also looked at `python-imports.cfg` which seems to contain some of the modules but not really third party modules.

**Comment by rbhanot4739** [comment]
@mgedmin So I generated the tags but see how the plugin imports the module. So I am using flask library and wanted to use `render_template` function and the i way would have expected the import statement to be something like this.
**Existing Flask Import statement**
`from flask import Flask`
Expected result
`from flask import Flask, render_template`

Basically it should append to the existing import statement if it exists otherwise it should create new. That said I could have been okay even if I would have created a new import statement like below.
` form flask import render_template`

**Result I get when i do :ImportName**

`from flask.templating import render_template`

**Comment by mgedmin** [comment]
> Can you please explain the hack, because for now it seems to add import statements randomly even if there is a import statement at the top of the file.

At the top of the file it skips a docstring (if present, and assuming it uses `"""`), then looks for any import statements, then the first blank line after that.

There's also some logic that tries to group related imports together.

I'd appreciate examples of files where the logic goes wrong.

(Usually I have trouble with the very first import in a blank line, where the "find first blank line" logic jumps a bit too far down.  I tend to fix it manually and all subsequent imports work fine for me)

**Comment by mgedmin** [comment]
> Hey sorry for bugging you again on this, it looks like my site-packages are not being imported with tag not found which seems logical since tags file does not have python third party modules since my conda env is at a different location.

What I do is I use a shell script that runs a Python one-liner to extract `sys.path` from your virtualenv or whatever, and then runs ctags and passes all the directories from `sys.path`.

It's called [`buildout-tags`](https://github.com/mgedmin/scripts/blob/master/buildout-tags) because I originally wrote it for projects that user zc.buildout, but it works with any Python environment.

**Comment by rbhanot4739** [comment]
I think i was able to fix the above issues, but my recent issue (example of flask imports) is the one bugging me.

**Comment by mgedmin** [comment]
Re. flask.render_template, there are two problems here:

- my plugin doesn't know how to extend existing import statements
- there's no way to determine the "official" import location if the function is defined elsewhere and then re-exported

The first is kind of annoying, and what I've been doing is joining the two imports together by hand, using something like `k`, `A,<esc>`, `J`, `l`, `d3W`.  A proper fix is, of course, possible, but I don't think I could do it in vimscript, and rewriting the whole plugin in Python is also a lot of work that I don't think I'll find the time to do in the foreseeable future.

(I wonder if other plugins, like vim-isort, could fix up these duplicate imports already?)

The second problem is impossible to fix -- there's no standard machine-readable way of defining the official API locations of functions that are defined in some other module.  I have a heuristic -- if the name being imported is in a private module (i.e. a module name starting with a `_`), I assume the actual API location is the parent package.  I also have a user-configurable workaround (the `python-imports.cfg` file).
