### ISSUE TITLE
Erroneous behaviour when and import is broken using parentheses

### ISSUE THREAD

**Issue by jytug** [mgedmin/python-imports.vim#4]
Hi,
I stumbled upon this when working on a larger project, but manager to create this minimal example.
Suppose the directory / module structure in our project is:

```
.
├── __init__.py
├── submodule1
│   ├── __init__.py
│   └── yo.py
└── submodule2
    ├── __init__.py
    └── dawg.py

2 directories, 5 files
```
where `yo.py` contains an empty function `yo` and `dawg.py` contains an empty function `dawg`.

The problem happens when `dawg` is imported from a script in the root directory like this:
```
from module.submodule2 import (
    dawg
)
```

Then, calling `:ImportName yo` results in the following:

```
from module.submodule2 import (
    from module.submodule1 import yo
    dawg
)
```

**Comment by mgedmin** [comment]
Thank you for the bug report!  It gave me an incentive to try and add better support for parenthesized multi-line import statements.
