### ISSUE TITLE
ImportName has to be called twice when more than one tag exists with same name

### ISSUE THREAD

**Issue by farfanoide** [mgedmin/python-imports.vim#5]
when tag has more than one instance then i have to call 2 times ImportName, only the second time will work, not first one.

**Comment by mgedmin** [comment]
I cannot reproduce.  What I tried:

```
mkdir /tmp/test
cd /tmp/test
echo 'def f(): pass' > a.py
echo 'def f(): pass' > b.py
ctags -R .
vim c.py
```

typed

```python


f()
```

pressed my keybinding to trigger :ImportName

got a selection menu to pick between a.py and b.py (the one vim shows on :tselect f), selected a

ended up with

```python


from a import f
f()
```

which is not 100% correct wrt whitespace, but seems to be working.

**Comment by farfanoide** [comment]
must be something relatedto my vimrc. closing now.
thanks

**Comment by mgedmin** [comment]
If you figure out what vimrc settings make this fail, please reopen!

**Comment by arthur-s** [comment]
I'm experiencing same issue, when I need to call ImportName twice, when there's more than one occurrence in tags file.

**Comment by mgedmin** [comment]
Does anything happen when you do :ImportName the first time?  Vim errors, confirmation prompts, split windows appearing, etc?

Do you have 'hidden' set?

**Comment by arthur-s** [comment]
Hi, thanks for response.
Yes, I have `set hidden` in my vimrc. If I comment  it, ImportNameHere doesn't work at all!

**Comment by arthur-s** [comment]
I've debugged script with echoes, and output [on line 294 is](https://github.com/mgedmin/python-imports.vim/blob/0a9835927417b545323e54bed3aad668e91816ca/plugin/python-imports.vim#L294):
```
E225: global mapping already exists for ic
```

**Comment by mgedmin** [comment]
Oooh, that is very interesting!

Do you have any autocommands/plugins that might be trying to remap `ic`?

Does commit 7c4c27b help?

**Comment by farfanoide** [comment]
worked like a charm for me

thanks @arthur-s for debugging and @mgedmin for fixing this.

cheers

**Comment by arthur-s** [comment]
@mgedmin yes, I have [textobj-python](https://github.com/bps/vim-textobj-python) plugin, which owerrides mapping for `ic`.
And I've tested your fix, it works well now, thanks a lot!

**Comment by mgedmin** [comment]
Thank you for debugging this!
